# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃
      uses: actions/checkout@v2
      with:
        path: portfolio/back  # 프로젝트를 저장할 경로 지정

    - name: JDK 17 설정
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 디렉토리 내용 표시
      run: ls -R ./portfolio/back

    - name: gradlew에 실행 권한 부여
      run: chmod +x ./portfolio/back/back/gradlew
      working-directory: portfolio/back/back # 명령을 실행할 디렉토리 지정

    - name: 권한 부여 후 디렉토리 내용 표시
      run: ls -R ./portfolio/back/back

    - name: Gradle Wrapper로 빌드
      run: |
        cd ./portfolio/back
        ./gradlew clean build --exclude-task test
    - name: Build with Gradle Wrapper
      run: |
        cd ./portfolio/back/back
        ./gradlew clean build --exclude-task test
