# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: portfolio/back  # Specify the path where you want to store the project

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Display directory contents
      run: ls -R ./portfolio/back

    - name: Grant execute permission for gradlew
      run: chmod +x ./portfolio/back/gradlew
      working-directory: portfolio/back  # Specify the working directory for the command

    - name: Display directory contents after chmod
      run: ls -R ./portfolio/back

    - name: Build with Gradle Wrapper
      run: |
        cd ./portfolio/back
        ./gradlew clean build --exclude-task test
